version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    ports:
      - "8080:8080"
